arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  position_only_ik: True
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5
  kinematics_solver_attempts: 1000
  solve_type: Distance